NETWORK_DIAGRAMS = [
    # --- SET 1 ---
    {
        "slug": "suspect-witness-network",
        "set_group": 1,
        "title": "Task 3A: Network Diagram 1",
        "type": "network",
        "order":"2",
        "context": "This diagram shows different social-media actions between a person, a group, a post, and a comment.",
        "image_url": "https://datawalk.com/wp-content/uploads/2021/05/Network-Graph-Example-1024x787.png.webp",
        "image_alt": "A network graph example with colored nodes and connecting links.",
        "image_source_label": "Provided network image 1",
        "image_source_url": "https://datawalk.com/wp-content/uploads/2021/05/Network-Graph-Example-1024x787.png.webp",
        "image_fit": "contain",
        "image_position": "center center",
        "image_aspect_ratio": "5 / 3",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "According to the diagram, who is shown as the witness to the murder?",
        "question_one_options": ["Mark Watkins", "Samuel Booker", "Alexander Miller", "No witness is shown"],
        "question_two": "Which person is identified as the suspect in the diagram?",
        "question_two_options": ["Samuel Booker", "Alexander Miller", "Mark Watkins", "The suspect is not labeled"],
    },
    {
        "slug": "social-network-example",
        "set_group": 2,
        "title": "Task 3B: Network Diagram 2",
        "type": "network",
        "order":"2",
        "context": "This network image uses circles and lines to show direct relationships. Compare central nodes with outer ones.",
        "image_url": "https://cdn.geekwire.com/wp-content/uploads/2018/05/What-is-graph-database-social-network-diagram.a6601377b99c03ede1f2e5cf078c01467fb6890a.png",
        "image_alt": "A social network diagram with many nodes and connecting lines.",
        "image_source_label": "Provided network image 2",
        "image_source_url": "https://cdn.geekwire.com/wp-content/uploads/2018/05/What-is-graph-database-social-network-diagram.a6601377b99c03ede1f2e5cf078c01467fb6890a.png",
        "image_fit": "contain",
        "image_position": "center center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "In the image, what kind of relationship is shown between people like Justin, Anna, or Alana?",
        "question_one_options": ["Friend relationships", "Murder-witness relationships", "Medical relationships", "Teacher-student relationships"],
        "question_two": "When a person is connected to items like books or movies in the image, what does that most likely represent?",
        "question_two_options": ["The person's interests or likes", "The person's age", "The person's job title", "The person's location"],
    },
    {
        "slug": "social-network-photo-diagram",
        "set_group": 3,
        "title": "Task 3C: Network Diagram 3",
        "type": "network",
        "order":"2",
        "context": "This image shows a social network with clearly visible nodes and links. Focus on direct relationships and peripheral nodes.",
        "image_url": "https://www.mbaskool.com/2019_images/stories/apr_images/social-network.jpg",
        "image_alt": "A simplified social network diagram with connected circles.",
        "image_source_label": "Provided network image 3",
        "image_source_url": "https://www.mbaskool.com/2019_images/stories/apr_images/social-network.jpg",
        "image_fit": "contain",
        "image_position": "center center",
        "image_aspect_ratio": "1 / 1",
        "image_scale": "70%",
        "nodes": [],
        "edges": [],
        "question_one": "Which label is placed in the center of the picture and linked directly to every surrounding circle?",
        "question_one_options": ["Social Network", "Brand Exposure", "Influence Presence", "Inter-Connected People"],
        "question_two": "Which of the following is shown as one of the direct benefits or outcomes linked to the center?",
        "question_two_options": ["Brand Exposure", "Medical Diagnosis", "Political Stability", "Weather Forecasting"],
    },

    # --- SET 2 ---
    {
        "slug": "environment-word-cloud",
        "set_group": 1,
        "title": "Task 3D: Word Cloud 1",
        "type": "wordcloud",
        "order":"1",
        "context": "Use the largest words to identify the main theme of the image.",
        "image_url": "https://as2.ftcdn.net/v2/jpg/04/21/53/99/1000_F_421539998_nMLPV86Aro7imZFGyYHqeNrPDJRo3p7h.jpg",
        "image_alt": "A simple word cloud with environment and nature related terms.",
        "image_source_label": "Provided word cloud 1",
        "image_source_url": "https://as2.ftcdn.net/v2/jpg/04/21/53/99/1000_F_421539998_nMLPV86Aro7imZFGyYHqeNrPDJRo3p7h.jpg",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "What is the largest and most prominently displayed word in the word cloud?",
        "question_one_options": ["Earth", "Environment", "Nature", "Ecology"],
        "question_two": "Which of the following words is NOT visible in the word cloud?",
        "question_two_options": ["Rivers", "Flora", "Insects", "Ocean"],
    },
    {
        "slug": "employee-word-cloud",
        "set_group": 2,
        "title": "Task 3E: Word Cloud 2",
        "type": "wordcloud",
        "order":"1",
        "context": "Look at the biggest words first, then use the smaller words to confirm the topic.",
        "image_url": "https://as2.ftcdn.net/v2/jpg/03/37/85/73/1000_F_337857354_XrVGNyV3axqeB6JjX4f8dgT1gSt5ZWZw.jpg",
        "image_alt": "A simple health themed word cloud.",
        "image_source_label": "Provided word cloud 2",
        "image_source_url": "https://as2.ftcdn.net/v2/jpg/03/37/85/73/1000_F_337857354_XrVGNyV3axqeB6JjX4f8dgT1gSt5ZWZw.jpg",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "What is the general theme/topic of this word cloud?",
        "question_one_options": ["Healthcare and Medicine", "Technology and Innovation", "Workplace and Employee Relations", "Education and Learning"],
        "question_two": "Which of the following concepts is clearly associated with employee experience in the image?",
        "question_two_options": ["Agriculture", "Space Exploration", "Equality", "Ocean Life"],
    },
    {
        "slug": "education-word-cloud",
        "set_group": 3,
        "title": "Task 3F: Word Cloud 3",
        "type": "wordcloud",
        "order":"1",
        "context": "Focus on the most prominent words to identify the main subject area.",
        "image_url": "https://as1.ftcdn.net/v2/jpg/02/71/85/78/1000_F_271857811_4atA14pwr3AhOY54T9qUcYs1HytJBUI5.jpg",
        "image_alt": "A simple business themed word cloud.",
        "image_source_label": "Provided word cloud 3",
        "image_source_url": "https://as1.ftcdn.net/v2/jpg/02/71/85/78/1000_F_271857811_4atA14pwr3AhOY54T9qUcYs1HytJBUI5.jpg",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "Which subject-related word appears vertically (rotated 90°) in the word cloud?",
        "question_one_options": ["Agriculture", "Infrastructure", "College", "Weather"],
        "question_two": "How many of these four words appear in the cloud — Library, Paper, Wisdom, Exam?",
        "question_two_options": ["One", "Three", "Two", "All four"],
    },

    # --- SET 3 ---
    {
        "slug": "bengaluru-metro-map",
        "set_group": 1,
        "title": "Task 3G: Bengaluru Metro Map",
        "type": "metromap",
        "order":"3",
        "context": "Examine the map and answer the questions",
        "image_url":"/static/survey_app/images/metromapblr.png",
        "image_alt": "Metro Map for Bengaluru",
        "image_source_label": "Blr metro map",
        "image_source_url": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Metro_Map_2025_-_Bengaluru_City.pdf",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "From Bommasandra to the airport,how many interchanges are present in the shortest path?",
        "question_one_options": ["Four", "Three", "Five", "Six"],
        "question_two": "How many interchange stations are visible in the map?",
        "question_two_options": ["Eight", "Five", "Seven", "Six"],
    },
    {
        "slug": "delhi-metro-map",
        "set_group":2,
        "title": "Task 3H: Delhi Metro Map",
        "type": "metromap",
        "order":"3",
        "context": "Examine the map and answer the questions",
        "image_url": "/static/survey_app/images/metromapdelhi.png",
        "image_alt": "Delhi Metro Map",
        "image_source_label": "Delhi metro map",
        "image_source_url": "https://www.nobroker.in/blog/wp-content/uploads/2025/01/delhi-metro-yellow-line-map.webp",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "From Badarpur to the airport,how many interchanges are present in the shortest path?",
        "question_one_options": ["Two", "Three", "Four", "Five"],
        "question_two": "How many interchange stations are visible in the map?",
        "question_two_options": ["Eight", "Nine", "Six","Five"],
    },
    {
        "slug": "singapore-metro-map",
        "set_group": 3,
        "title": "Task 3I: Singapore Metro Map",
        "type": "metromap",
        "order":"3",
        "context": "Examine the map and answer the questions",
        "image_url": "/static/survey_app/images/metromapsg.png",
        "image_alt": "Metro Map of Singapore",
        "image_source_label": "Singapore Metro Map",
        "image_source_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Singapore-MRT.png/1920px-Singapore-MRT.png?utm_source=es.wikivoyage.org&utm_campaign=index&utm_content=thumbnail",
        "image_fit": "contain",
        "image_position": "center center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "From Joo Koon to Punggol, how many interchanges are present in the shortest path?",
        "question_one_options": ["Three", "Four", "Five", "Six"],
        "question_two": "How many interchange stations are visible in the map?",
        "question_two_options": ["Ten", "Twelve", "Thirteen", "Eleven"],
    },

]