NETWORK_DIAGRAMS = [
    # --- SET 1 ---
    {
        "slug": "marketing-technology-network",
        "set_group": 1,
        "title": "Task 3A: Network Diagram 1",
        "type": "network",
        "context": "This diagram shows different social-media actions between a person, a group, a post, and a comment.",
        "image_url": "https://datawalk.com/wp-content/uploads/2021/05/Network-Graph-Example-1024x787.png.webp",
        "image_alt": "A network graph example with colored nodes and connecting links.",
        "image_source_label": "Provided network image 1",
        "image_source_url": "https://datawalk.com/wp-content/uploads/2021/05/Network-Graph-Example-1024x787.png.webp",
        "image_fit": "contain",
        "image_position": "center center",
        "image_aspect_ratio": "5 / 3",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "According to the diagram, who is shown as the witness to the murder?",
        "question_one_options": ["Mark Watkins", "Samuel Booker", "Alexander Miller", "No witness is shown"],
        "question_two": "Which person is identified as the suspect in the diagram?",
        "question_two_options": ["Samuel Booker", "Alexander Miller", "Mark Watkins", "The suspect is not labeled"],
    },
    {
        "slug": "social-network-example",
        "set_group": 1,
        "title": "Task 3B: Network Diagram 2",
        "type": "network",
        "context": "This network image uses circles and lines to show direct relationships. Compare central nodes with outer ones.",
        "image_url": "https://cdn.geekwire.com/wp-content/uploads/2018/05/What-is-graph-database-social-network-diagram.a6601377b99c03ede1f2e5cf078c01467fb6890a.png",
        "image_alt": "A social network diagram with many nodes and connecting lines.",
        "image_source_label": "Provided network image 2",
        "image_source_url": "https://cdn.geekwire.com/wp-content/uploads/2018/05/What-is-graph-database-social-network-diagram.a6601377b99c03ede1f2e5cf078c01467fb6890a.png",
        "image_fit": "contain",
        "image_position": "center center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "In the image, what kind of relationship is shown between people like Justin, Anna, or Alana?",
        "question_one_options": ["Friend relationships", "Murder-witness relationships", "Medical relationships", "Teacher-student relationships"],
        "question_two": "When a person is connected to items like books or movies in the image, what does that most likely represent?",
        "question_two_options": ["The person's interests or likes", "The person's age", "The person's job title", "The person's location"],
    },
    {
        "slug": "social-network-photo-diagram",
        "set_group": 1,
        "title": "Task 3C: Network Diagram 3",
        "type": "network",
        "context": "This image shows a social network with clearly visible nodes and links. Focus on direct relationships and peripheral nodes.",
        "image_url": "https://www.mbaskool.com/2019_images/stories/apr_images/social-network.jpg",
        "image_alt": "A simplified social network diagram with connected circles.",
        "image_source_label": "Provided network image 3",
        "image_source_url": "https://www.mbaskool.com/2019_images/stories/apr_images/social-network.jpg",
        "image_fit": "contain",
        "image_position": "center center",
        "image_aspect_ratio": "1 / 1",
        "image_scale": "70%",
        "nodes": [],
        "edges": [],
        "question_one": "Which label is placed in the center of the picture and linked directly to every surrounding circle?",
        "question_one_options": ["Social Network", "Brand Exposure", "Influence Presence", "Inter-Connected People"],
        "question_two": "Which of the following is shown as one of the direct benefits or outcomes linked to the center?",
        "question_two_options": ["Brand Exposure", "Medical Diagnosis", "Political Stability", "Weather Forecasting"],
    },

    # --- SET 2 ---
    {
        "slug": "environment-word-cloud",
        "set_group": 2,
        "title": "Task 3D: Word Cloud 1",
        "type": "wordcloud",
        "context": "Use the largest words to identify the main theme of the image.",
        "image_url": "https://as2.ftcdn.net/v2/jpg/04/21/53/99/1000_F_421539998_nMLPV86Aro7imZFGyYHqeNrPDJRo3p7h.jpg",
        "image_alt": "A simple word cloud with environment and nature related terms.",
        "image_source_label": "Provided word cloud 1",
        "image_source_url": "https://as2.ftcdn.net/v2/jpg/04/21/53/99/1000_F_421539998_nMLPV86Aro7imZFGyYHqeNrPDJRo3p7h.jpg",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "What is the largest and most prominently displayed word in the word cloud?",
        "question_one_options": ["Earth", "Environment", "Nature", "Ecology"],
        "question_two": "Which of the following words is NOT visible in the word cloud?",
        "question_two_options": ["Rivers", "Flora", "Insects", "Ocean"],
    },
    {
        "slug": "health-word-cloud",
        "set_group": 2,
        "title": "Task 3E: Word Cloud 2",
        "type": "wordcloud",
        "context": "Look at the biggest words first, then use the smaller words to confirm the topic.",
        "image_url": "https://as2.ftcdn.net/v2/jpg/03/37/85/73/1000_F_337857354_XrVGNyV3axqeB6JjX4f8dgT1gSt5ZWZw.jpg",
        "image_alt": "A simple health themed word cloud.",
        "image_source_label": "Provided word cloud 2",
        "image_source_url": "https://as2.ftcdn.net/v2/jpg/03/37/85/73/1000_F_337857354_XrVGNyV3axqeB6JjX4f8dgT1gSt5ZWZw.jpg",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "What is the general theme/topic of this word cloud?",
        "question_one_options": ["Healthcare and Medicine", "Technology and Innovation", "Workplace and Employee Relations", "Education and Learning"],
        "question_two": "Which of the following concepts is clearly associated with employee experience in the image?",
        "question_two_options": ["Agriculture", "Space Exploration", "Equality", "Ocean Life"],
    },
    {
        "slug": "business-word-cloud",
        "set_group": 2,
        "title": "Task 3F: Word Cloud 3",
        "type": "wordcloud",
        "context": "Focus on the most prominent words to identify the main subject area.",
        "image_url": "https://as1.ftcdn.net/v2/jpg/02/71/85/78/1000_F_271857811_4atA14pwr3AhOY54T9qUcYs1HytJBUI5.jpg",
        "image_alt": "A simple business themed word cloud.",
        "image_source_label": "Provided word cloud 3",
        "image_source_url": "https://as1.ftcdn.net/v2/jpg/02/71/85/78/1000_F_271857811_4atA14pwr3AhOY54T9qUcYs1HytJBUI5.jpg",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "Which subject-related word appears vertically (rotated 90°) in the word cloud?",
        "question_one_options": ["College", "Science", "School", "University"],
        "question_two": "How many of these four words appear in the cloud — Library, Paper, Wisdom, Exam?",
        "question_two_options": ["One", "Three", "Two", "All four"],
    },

    # --- SET 3 ---
    {
        "slug": "bengaluru-metro-map",
        "set_group": 3,
        "title": "Task 3G: Metro Map",
        "type": "metromap",
        "context": "Answer the questions by interpreting the diagram",
        "image_url":"/static/survey_app/images/metro_map.jpg",
        "image_alt": "Metro Map for Bengaluru",
        "image_source_label": "Blr metro map",
        "image_source_url": "/stat",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "From Electronic City to the airport,how many interchanges are there in the shortest path?",
        "question_one_options": ["Four", "Three", "Five", "Six"],
        "question_two": "How many interchange stations are visible in the map?",
        "question_two_options": ["Eight", "Five", "Seven", "Six"],
    },
    {
        "slug": "spurious-correlation-graph",
        "set_group":3,
        "title": "Task 3H: Correlation Graph",
        "type": "graph",
        "context": "",
        "image_url": "/static/survey_app/images/spuriouscorrelation.png",
        "image_alt": "A correlation graph",
        "image_source_label": "Correlation graph",
        "image_source_url": "https://as2.ftcdn.net/v2/jpg/01/87/00/22/1000_F_187002272_QG4x9f6Xf8hJ7V8t8j9Tj8H9yH9h9h9.jpg",
        "image_fit": "contain",
        "image_position": "left center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "Is the distance between Saturn and the Sun correlated with biomass power generated in India?",
        "question_one_options": ["Yes", "No", "Cannot Say"],
        "question_two": "Does the distance between Saturn and the Sun cause the biomass power generated in India?",
        "question_two_options": ["Yes", "No", "Cannot Say"],
    },
    {
        "slug": "finance-network-diagram",
        "set_group": 3,
        "title": "Task 3I: Network Diagram 4",
        "type": "network",
        "context": "Examine the flows and connections between different financial entities in the diagram.",
        "image_url": "https://datawalk.com/wp-content/uploads/2021/05/Network-Graph-Example-1024x787.png.webp",
        "image_alt": "A network graph showing financial transactions.",
        "image_source_label": "Provided network image 4",
        "image_source_url": "https://datawalk.com/wp-content/uploads/2021/05/Network-Graph-Example-1024x787.png.webp",
        "image_fit": "contain",
        "image_position": "center center",
        "image_scale": "100%",
        "nodes": [],
        "edges": [],
        "question_one": "What is the central node facilitating these connections?",
        "question_one_options": ["Central Bank", "Investment Firm", "Retail Customer", "Clearing House"],
        "question_two": "What type of links connect the outer nodes to the center?",
        "question_two_options": ["Transactions", "Friendships", "Emails", "Physical Roads"],
    },
]