# Generated by Django 5.2.15 on 2026-06-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('survey_app', '0009_paasresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='targeted_movies', to='auth.group'),
        ),
        migrations.AddField(
            model_name='networkdiagram',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='targeted_diagrams', to='auth.group'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='targeted_news', to='auth.group'),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
