# Generated by Django 5.2.15 on 2026-06-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0011_participant_expertise_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkdiagram',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='networkdiagram',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
