# Generated by Django 5.2.15 on 2026-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0012_alter_networkdiagram_options_networkdiagram_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='paasresponse',
            name='item_difficulty_ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
