# Generated by Django 5.2.15 on 2026-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0013_paasresponse_item_difficulty_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdiagram',
            name='type',
            field=models.CharField(default='network', max_length=20),
            preserve_default=False,
        ),
    ]
