# Generated by Django 5.2.15 on 2026-07-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0014_networkdiagram_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsession',
            name='movies_per_week',
        ),
        migrations.RemoveField(
            model_name='participantsession',
            name='picture_statement_agreement',
        ),
        migrations.RemoveField(
            model_name='participantsession',
            name='reading_habits_completed_at',
        ),
        migrations.RemoveField(
            model_name='participantsession',
            name='reads_news_daily',
        ),
        migrations.RemoveField(
            model_name='participantsession',
            name='reads_words_daily',
        ),
    ]